sudo: false
language: java
jdk:
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/org/joda/money
# install
install:
  - mvn --version
script:
  - mvn install site -e -B
after_success:
  - if [[ $TRAVIS_TAG =~ ^v.*$ ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk10" ]; then travis_wait 40 mvn clean install site-deploy -e -B --settings .github/maven-settings.xml; fi
# secure keys for GITHUB_TOKEN, OSS_SONATYPE
env:
  global:
  - secure: RkVwVb42aCiC2WHf1vuKZizw7HB3L0WLA3Sk3uI/doCj8UBI4gahoduClPFJKAs8xTgRFijUXDPtBEzOmVYaverwX2K62Ui0ddhhXWsk+U4bWHVkhJ/QEs07Z0ddBhbEv4TicFhNAlGKezSMIMfFpfW2b2JrjWDVO6Exj3ndUCQ=
  - secure: h8Ov3DIeL8c6wtOk9wej9gnyo1iA1nj6wlNWB4CZSb4uyXfupv4FlcIamB4hFsGzUwF61SJ47n76DjZHzV7fUKVmDzWQfIJ/N1rnYJNR8qRgS8g1d1i8RccZyqndcGrTkpKhAGOQ8Py5PSXaApRnzirn5aqkIeYZeAwNkiVVUhE=
